version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: surakshit_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: surakshit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
